DROP TABLE se CASCADE;

DROP FUNCTION IF EXISTS se_rd( varchar ) CASCADE;
DROP FUNCTION IF EXISTS se_x( varchar ) CASCADE;
DROP FUNCTION IF EXISTS se_wr( varchar, int, text ) CASCADE;
DROP FUNCTION IF EXISTS se_ch( varchar, varchar ) CASCADE;
DROP FUNCTION IF EXISTS se_de( varchar ) CASCADE;
DROP FUNCTION IF EXISTS se_gc() CASCADE;
