-- function grants
GRANT EXECUTE ON FUNCTION _sec( varchar ) TO GROUP sys;
GRANT EXECUTE ON FUNCTION _sec( varchar ) TO GROUP app;
GRANT EXECUTE ON FUNCTION _sec( varchar ) TO GROUP usr;
--
GRANT EXECUTE ON FUNCTION _time() TO GROUP sys;
GRANT EXECUTE ON FUNCTION _time() TO GROUP app;
GRANT EXECUTE ON FUNCTION _time() TO GROUP usr;
--
GRANT EXECUTE ON FUNCTION _msec() TO GROUP sys;
GRANT EXECUTE ON FUNCTION _msec() TO GROUP app;
GRANT EXECUTE ON FUNCTION _msec() TO GROUP usr;
--
GRANT EXECUTE ON FUNCTION _ts() TO GROUP sys;
GRANT EXECUTE ON FUNCTION _ts() TO GROUP app;
GRANT EXECUTE ON FUNCTION _ts() TO GROUP usr;
